package com.qaschool.hapifyme.model;

import java.time.Instant;
import java.util.Map;

// Represents a unique HapifyMe user used by the UI automation scenarios.
public class TestUser {
    private final String firstName;
    private final String lastName;
    private final String email;
    private final String password;

    private TestUser(String firstName, String lastName, String email, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
    }

    // Builds a unique test user from a Cucumber Data Table.
    public static TestUser fromDataTable(Map<String, String> data) {
        String suffix = String.valueOf(Instant.now().toEpochMilli());
        String firstName = data.get("firstName");
        String lastName = data.get("lastName") + suffix.substring(suffix.length() - 6);
        String email = "qa.cucumber." + suffix + "@example.com";
        String password = data.get("password");

        return new TestUser(firstName, lastName, email, password);
    }

    // Creates the default user used by scenarios that need a registered account.
    public static TestUser uniqueDefaultUser() {
        return fromDataTable(Map.of(
                "firstName", "Radu",
                "lastName", "Cucumber",
                "password", "StrongPass123!"
        ));
    }

    // Returns the user's first name.
    public String getFirstName() {
        return firstName;
    }

    // Returns the user's last name.
    public String getLastName() {
        return lastName;
    }

    // Returns the user's email address.
    public String getEmail() {
        return email;
    }

    // Returns the user's password.
    public String getPassword() {
        return password;
    }

    // Returns the username expected to be generated by HapifyMe from the first and last name.
    public String getExpectedUsername() {
        return (firstName + "_" + lastName).toLowerCase();
    }

    // Returns the user's full display name.
    public String getFullName() {
        return firstName + " " + lastName;
    }
}
